### ISSUE TITLE
CI fails unless you clear caches first

### ISSUE THREAD

**Issue by SethTisue** [lightbend-labs/dbuild#237]
the failures look like:

```
[info] 	published ivy to /home/runner/.ivy2/local/com.typesafe.dbuild/build_2.10/0.9.18/ivys/ivy.xml
[8396](https://github.com/lightbend-labs/dbuild/actions/runs/3569309105/jobs/5999133281#step:5:8397)
java.lang.IllegalStateException: Ivy file not found in cache for com.typesafe.dbuild#dbuild;0.9.18!
[8397](https://github.com/lightbend-labs/dbuild/actions/runs/3569309105/jobs/5999133281#step:5:8398)
	at sbt.ResolutionCache.getResolvedModuleDescriptor(ResolutionCache.scala:52)
[8398](https://github.com/lightbend-labs/dbuild/actions/runs/3569309105/jobs/5999133281#step:5:8399)
	at org.apache.ivy.core.deliver.DeliverEngine.deliver(DeliverEngine.java:111)
[8399](https://github.com/lightbend-labs/dbuild/actions/runs/3569309105/jobs/5999133281#step:5:8400)
	at org.apache.ivy.Ivy.deliver(Ivy.java:601)
[8400](https://github.com/lightbend-labs/dbuild/actions/runs/3569309105/jobs/5999133281#step:5:8401)
	at sbt.IvyActions$$anonfun$deliver$1.apply(IvyActions.scala:108)
[8401](https://github.com/lightbend-labs/dbuild/actions/runs/3569309105/jobs/5999133281#step:5:8402)
	at sbt.IvyActions$$anonfun$deliver$1.apply(IvyActions.scala:103)
[8402](https://github.com/lightbend-labs/dbuild/actions/runs/3569309105/jobs/5999133281#step:5:8403)
	at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:156)
[8403](https://github.com/lightbend-labs/dbuild/actions/runs/3569309105/jobs/5999133281#step:5:8404)
	at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:156)
[8404](https://github.com/lightbend-labs/dbuild/actions/runs/3569309105/jobs/5999133281#step:5:8405)
	at sbt.IvySbt$$anonfun$withIvy$1.apply(Ivy.scala:133)
[8405](https://github.com/lightbend-labs/dbuild/actions/runs/3569309105/jobs/5999133281#step:5:8406)
	at sbt.IvySbt.sbt$IvySbt$$action$1(Ivy.scala:57)
[8406](https://github.com/lightbend-labs/dbuild/actions/runs/3569309105/jobs/5999133281#step:5:8407)
	at sbt.IvySbt$$anon$4.call(Ivy.scala:65)
[8407](https://github.com/lightbend-labs/dbuild/actions/runs/3569309105/jobs/5999133281#step:5:8408)
	at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:113)
[8408](https://github.com/lightbend-labs/dbuild/actions/runs/3569309105/jobs/5999133281#step:5:8409)
	at xsbt.boot.Locks$GlobalLock.withChannelRetries$1(Locks.scala:91)
[8409](https://github.com/lightbend-labs/dbuild/actions/runs/3569309105/jobs/5999133281#step:5:8410)
	at xsbt.boot.Locks$GlobalLock.$anonfun$withFileLock$1(Locks.scala:119)
[8410](https://github.com/lightbend-labs/dbuild/actions/runs/3569309105/jobs/5999133281#step:5:8411)
	at xsbt.boot.Using$.withResource(Using.scala:12)
[8411](https://github.com/lightbend-labs/dbuild/actions/runs/3569309105/jobs/5999133281#step:5:8412)
	at xsbt.boot.Using$.apply(Using.scala:9)
[8412](https://github.com/lightbend-labs/dbuild/actions/runs/3569309105/jobs/5999133281#step:5:8413)
	at xsbt.boot.Locks$GlobalLock.withFileLock(Locks.scala:119)
[8413](https://github.com/lightbend-labs/dbuild/actions/runs/3569309105/jobs/5999133281#step:5:8414)
	at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:71)
[8414](https://github.com/lightbend-labs/dbuild/actions/runs/3569309105/jobs/5999133281#step:5:8415)
	at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:59)
[8415](https://github.com/lightbend-labs/dbuild/actions/runs/3569309105/jobs/5999133281#step:5:8416)
	at xsbt.boot.Locks$.apply0(Locks.scala:47)
[8416](https://github.com/lightbend-labs/dbuild/actions/runs/3569309105/jobs/5999133281#step:5:8417)
	at xsbt.boot.Locks$.apply(Locks.scala:36)
[8417](https://github.com/lightbend-labs/dbuild/actions/runs/3569309105/jobs/5999133281#step:5:8418)
	at sbt.IvySbt.withDefaultLogger(Ivy.scala:65)
[8418](https://github.com/lightbend-labs/dbuild/actions/runs/3569309105/jobs/5999133281#step:5:8419)
	at sbt.IvySbt.withIvy(Ivy.scala:128)
[8419](https://github.com/lightbend-labs/dbuild/actions/runs/3569309105/jobs/5999133281#step:5:8420)
	at sbt.IvySbt.withIvy(Ivy.scala:125)
[8420](https://github.com/lightbend-labs/dbuild/actions/runs/3569309105/jobs/5999133281#step:5:8421)
	at sbt.IvySbt$Module.withModule(Ivy.scala:156)
[8421](https://github.com/lightbend-labs/dbuild/actions/runs/3569309105/jobs/5999133281#step:5:8422)
	at sbt.IvyActions$.deliver(IvyActions.scala:103)
[8422](https://github.com/lightbend-labs/dbuild/actions/runs/3569309105/jobs/5999133281#step:5:8423)
	at sbt.Classpaths$$anonfun$deliverTask$1.apply(Defaults.scala:1455)
[8423](https://github.com/lightbend-labs/dbuild/actions/runs/3569309105/jobs/5999133281#step:5:8424)
	at sbt.Classpaths$$anonfun$deliverTask$1.apply(Defaults.scala:1455)
[8424](https://github.com/lightbend-labs/dbuild/actions/runs/3569309105/jobs/5999133281#step:5:8425)
	at scala.Function4$$anonfun$tupled$1.apply(Function4.scala:35)
[8425](https://github.com/lightbend-labs/dbuild/actions/runs/3569309105/jobs/5999133281#step:5:8426)
	at scala.Function4$$anonfun$tupled$1.apply(Function4.scala:34)
[8426](https://github.com/lightbend-labs/dbuild/actions/runs/3569309105/jobs/5999133281#step:5:8427)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
[8427](https://github.com/lightbend-labs/dbuild/actions/runs/3569309105/jobs/5999133281#step:5:8428)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
[8428](https://github.com/lightbend-labs/dbuild/actions/runs/3569309105/jobs/5999133281#step:5:8429)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
[8429](https://github.com/lightbend-labs/dbuild/actions/runs/3569309105/jobs/5999133281#step:5:8430)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
[8430](https://github.com/lightbend-labs/dbuild/actions/runs/3569309105/jobs/5999133281#step:5:8431)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
[8431](https://github.com/lightbend-labs/dbuild/actions/runs/3569309105/jobs/5999133281#step:5:8432)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
[8432](https://github.com/lightbend-labs/dbuild/actions/runs/3569309105/jobs/5999133281#step:5:8433)
	at sbt.Execute.work(Execute.scala:237)
[8433](https://github.com/lightbend-labs/dbuild/actions/runs/3569309105/jobs/5999133281#step:5:8434)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
[8434](https://github.com/lightbend-labs/dbuild/actions/runs/3569309105/jobs/5999133281#step:5:8435)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
[8435](https://github.com/lightbend-labs/dbuild/actions/runs/3569309105/jobs/5999133281#step:5:8436)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
[8436](https://github.com/lightbend-labs/dbuild/actions/runs/3569309105/jobs/5999133281#step:5:8437)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
[8437](https://github.com/lightbend-labs/dbuild/actions/runs/3569309105/jobs/5999133281#step:5:8438)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[8438](https://github.com/lightbend-labs/dbuild/actions/runs/3569309105/jobs/5999133281#step:5:8439)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[8439](https://github.com/lightbend-labs/dbuild/actions/runs/3569309105/jobs/5999133281#step:5:8440)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[8440](https://github.com/lightbend-labs/dbuild/actions/runs/3569309105/jobs/5999133281#step:5:8441)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[8441](https://github.com/lightbend-labs/dbuild/actions/runs/3569309105/jobs/5999133281#step:5:8442)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[8442](https://github.com/lightbend-labs/dbuild/actions/runs/3569309105/jobs/5999133281#step:5:8443)
	at java.lang.Thread.run(Thread.java:750)
[8443](https://github.com/lightbend-labs/dbuild/actions/runs/3569309105/jobs/5999133281#step:5:8444)
[error] (dist/*:deliverLocal) java.lang.IllegalStateException: Ivy file not found in cache for com.typesafe.dbuild#dbuild;0.9.18!
[8444](https://github.com/lightbend-labs/dbuild/actions/runs/3569309105/jobs/5999133281#step:5:8445)
[error] Total time: 27 s, completed Nov 28, 2022 10:51:46 PM
[8445](https://github.com/lightbend-labs/dbuild/actions/runs/3569309105/jobs/5999133281#step:5:8446)
Error: Process completed with exit code 1.
```

I think I've seen this locally as well and dealt with it by blowing away the relevant subdirectory of `~/.ivy2/local` ?

**Comment by SethTisue** [comment]
hmm... I had this happen on CI just now and there wasn't a cache

so that has me thinking maybe it's a race condition? like maybe `dist/*:deliverLocal` is running in parallel with other stuff instead of waiting for it to finish?
